### ISSUE TITLE
Need an endpoint to GET user's achievements

### ISSUE THREAD

**Issue by sebastienrichoz** [moodah/AMT_Gamification#10]
Needed to display his badges and what left him to get missing badges.
Something like
![image](https://cloud.githubusercontent.com/assets/5737238/22288030/7771fc4a-e2f5-11e6-8e33-28ff2267785d.png)

It would be great to have ALL badges and user's achievement for each of them

**Comment by moodah** [comment]
Done on GET /users/{id}
